begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) values('44444444-4444-4444-8444-444444444444','interview@example.test',now(),now(),now());
select public.linkedin_bootstrap_admin('44444444-4444-4444-8444-444444444444');
set local role anon;
select throws_ok($$select public.interview_snapshot()$$,'42501',null,'anonymous private access denied');
reset role;
set local role authenticated;
select throws_ok($$select public.interview_snapshot()$$,'42501','Admin access required','ordinary user denied');
select is((select count(*)::integer from public.interview_opportunities),0,'RLS hides opportunities');
select set_config('request.jwt.claims','{"sub":"44444444-4444-4444-8444-444444444444","role":"authenticated"}',true);
select is(public.interview_snapshot()->'profile'->>'version','0','empty profile is available');
select lives_ok($$select public.interview_save_profile('{"resume":"Actual resume","experience":"Evidenced story"}',0)$$,'profile saved');
select throws_ok($$select public.interview_save_profile('{"resume":"Changed","experience":""}',0)$$,'P0001','Profile changed. Refresh before saving.','stale profile rejected');
create temp table input as select '{"company":"Example","website":"https://example.com","position":"Engineer","jobUrl":"","jobDescription":"Role","notes":"Private","outcome":"","status":"potential","rounds":[{"label":"Technical","scheduledAt":"","timezone":"America/Los_Angeles","format":"Architecture","interviewer":"Person","interviewerTitle":"CTO","profileUrl":"https://example.com/person","notes":""}]}'::jsonb value;
create temp table saved as select public.interview_save(value,null,0,'create1') id from input;
select is((select count(*)::integer from public.interview_rounds),1,'round saved atomically');
select is((select public.interview_save(value,null,0,'create1') from input),(select id from saved),'create retry returns same record');
select throws_ok($$select public.interview_save(value||'{"position":"Other"}',null,0,'create1') from input$$,'P0001','Request key reused with different input','changed retry rejected');
select throws_ok($$select public.interview_save(value,(select id from saved),0,'edit1') from input$$,'P0001','Opportunity changed. Refresh before saving.','stale opportunity rejected');
select throws_ok($$select public.interview_save(value||'{"website":"javascript:alert(1)"}',null,0,'bad-url') from input$$,'22023','Invalid URL','unsafe URL rejected');
select throws_ok($$insert into public.interview_opportunities(company_id,input) select company_id,input from public.interview_opportunities$$,'42501',null,'direct client writes denied');
reset role;
create temp table brief as select jsonb_build_object('opportunityId',(select id from saved),'opportunityVersion',1,'profileVersion',1,'sections','{"company":"Business and competitors remain unverified.","fit":"Use the actual story.","likelyQuestions":"Predicted: how do you bound retries?","questionsToAsk":"Who buys the product? How is the business doing? What differentiates it?","studyPlan":"Practice durable jobs.","uncertainty":"Predictions are not reported company questions."}'::jsonb,'sources','[{"title":"Example","url":"https://example.com","verifiedAt":"2026-10-04","kind":"primary"}]'::jsonb,'resources','[]'::jsonb,'knowledge','{"status":"pending","warnings":["Local assessment pending"]}'::jsonb,'editing',jsonb_build_object('skill','technical-edit','skillHash',repeat('a',64),'draftHash',repeat('a',64),'editedHash',repeat('a',64),'compared',true)) value;
grant select on brief to authenticated;
update brief set value=jsonb_set(value,'{editing,editedHash}',to_jsonb(private.knowledge_hash(value->'sections')));
set local role authenticated;
select throws_ok($$select public.interview_import(value-'editing','missing-edit') from brief$$,'22023','Technical-edit comparison required','mandatory editing enforced');
select throws_ok($$select public.interview_import(jsonb_set(value,'{sections,fit}','"Changed after edit"'),'changed-prose') from brief$$,'22023','Edited prose changed after technical-edit finalization','editing receipt binds prose');
select lives_ok($$select public.interview_import(value,'import1') from brief$$,'edited draft imports');
select is((select count(*)::integer from public.interview_briefs),1,'one immutable revision');
select lives_ok($$select public.interview_import(value,'import1') from brief$$,'import retry succeeds');
select is((select count(*)::integer from public.interview_briefs),1,'retry does not duplicate history');
select throws_ok($$select public.interview_import(jsonb_set(value,'{profileVersion}','0'),'stale-profile') from brief$$,'P0001','Preparation inputs changed. Generate against current context.','stale profile brief denied');
select throws_ok($$select public.interview_assess(jsonb_set(value,'{profileVersion}','0'),'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa') from brief$$,'P0001','Preparation inputs changed','assessment rejects stale profile');
select throws_ok($$select public.interview_import(jsonb_set(value,'{knowledge}','{"status":"reviewed","warnings":[],"snapshotId":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","jobId":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"}'),'unreviewed') from brief$$,'P0001','Current accepted knowledge assessment required','prepared needs current accepted report');
reset role;
select public.knowledge_publish(jsonb_build_object('id',repeat('a',64),'source_catalog_id',repeat('b',64),'counts',jsonb_build_object('document',1),'resources',jsonb_build_array(jsonb_build_object('id','document:example','kind','document','title','Example lesson','hash',repeat('c',64),'text','Verified study evidence','route','/docs/example','visibility','curriculum','status','published','paths',jsonb_build_array('path:example'),'skills',jsonb_build_array('skill:example:design'))),'relationships','[]'::jsonb,'semantic_complete',false));
create temp table evidence as select jsonb_set(value,'{resources}',jsonb_build_array(jsonb_build_object('resourceId','document:example','hash',repeat('c',64),'title','Example lesson','quote','Verified study','route','/docs/example','paths',jsonb_build_array('path:example'),'skills',jsonb_build_array('skill:example:design')))) value from brief;
grant select on evidence to authenticated;
set local role authenticated;
select lives_ok($$select public.interview_import(value,'evidence-good') from evidence$$,'canonical study evidence imports');
select throws_ok($$select public.interview_import(jsonb_set(value,'{resources,0,route}','"/docs/other"'),'evidence-route') from evidence$$,'P0001','Study resource evidence is stale or missing','forged resource route rejected');
select throws_ok($$select public.interview_import(jsonb_set(value,'{resources,0,skills}','["skill:invented"]'),'evidence-skill') from evidence$$,'P0001','Study resource evidence is stale or missing','invented skill rejected');
select throws_ok($$select public.interview_import(jsonb_set(value,'{resources,0,hash}',to_jsonb(repeat('d',64))),'evidence-hash') from evidence$$,'P0001','Study resource evidence is stale or missing','stale resource hash rejected');
select lives_ok($$select public.interview_assess(value,'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb') from brief$$,'edited brief queues assessment');
reset role;
update public.knowledge_jobs set status='succeeded',report=jsonb_build_object('snapshot_id',repeat('b',64),'candidate_hash',candidate_hash,'action','needs_review','matches','[]'::jsonb,'relationships','[]'::jsonb,'warnings','[]'::jsonb,'placement','{}'::jsonb,'semantic_complete',false) where id='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
select public.knowledge_review('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',(select candidate_hash from public.knowledge_jobs where id='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'),repeat('b',64),'accept');
set local role authenticated;
select lives_ok($$select public.interview_import(jsonb_set(value,'{knowledge}',jsonb_build_object('status','reviewed','warnings','[]'::jsonb,'snapshotId',repeat('a',64),'jobId','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb')),'reviewed-good') from brief$$,'accepted exact-body assessment imports');
select throws_ok($$select public.interview_import(jsonb_set(value,'{knowledge}',jsonb_build_object('status','reviewed','warnings','[]'::jsonb,'snapshotId',repeat('b',64),'jobId','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb')),'reviewed-stale') from brief$$,'P0001','Current accepted knowledge assessment required','old graph assessment rejected');
select is((public.interview_snapshot()->'revisions'->0->'context'->>'company'),'Example','brief retains original opportunity context');
select is(jsonb_array_length(public.interview_snapshot()->'profileHistory'),1,'backup includes profile history');
select lives_ok($$select public.interview_save(value||'{"status":"archived"}',(select id from saved),1,'archive') from input$$,'archive preserves records');
select is((select count(*)::integer from public.interview_briefs),3,'archive retains preparation history');
select throws_ok($$select public.interview_import(value,'stale-opportunity') from brief$$,'P0001','Preparation inputs changed. Generate against current context.','stale opportunity brief denied');
reset role;
select throws_ok($$update public.interview_briefs set brief='{}'$$,'P0001','Interview revisions are immutable','history cannot be overwritten');
select throws_ok($$delete from public.interview_profiles$$,'P0001','Interview revisions are immutable','profile history cannot be deleted');
select * from finish();
rollback;
