begin;
select no_plan();
select has_table('public','knowledge_snapshots','Versioned snapshots exist');
select has_table('public','knowledge_jobs','Durable jobs exist');
select ok((select relrowsecurity from pg_class where oid='public.knowledge_resources'::regclass),'Graph resources have RLS');
select ok(not has_function_privilege('anon','public.knowledge_submit(jsonb,uuid)','EXECUTE'),'Anonymous users cannot submit');
select ok(not has_function_privilege('authenticated','public.knowledge_publish(jsonb)','EXECUTE'),'Browser users cannot publish snapshots');
select throws_ok($$select public.knowledge_browse()$$,'42501','Admin access required','Unauthenticated browsing is denied');
select lives_ok($$select public.knowledge_publish('{"id":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","source_catalog_id":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","counts":{"document":1},"resources":[{"id":"document:a","kind":"document","title":"A","hash":"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","text":"An index lesson","visibility":"curriculum","status":"published","paths":[],"skills":[]}],"relationships":[],"semantic_complete":false}'::jsonb)$$,'A complete explicit snapshot activates');
-- Reports carry bounded literal excerpts, while hashes bind the complete source version.
select ok(private.knowledge_report_valid(jsonb_build_object('action','needs_review','matches',jsonb_build_array(jsonb_build_object('id','document:a','hash',repeat('c',64),'text','index lesson')),'relationships','[]'::jsonb,'warnings','[]'::jsonb,'placement','{}'::jsonb,'semantic_complete',false),repeat('a',64)),'A literal source excerpt is valid evidence');
select ok(not private.knowledge_report_valid(jsonb_build_object('action','needs_review','matches',jsonb_build_array(jsonb_build_object('id','document:a','hash',repeat('c',64),'text','INDEX lesson')),'relationships','[]'::jsonb,'warnings','[]'::jsonb,'placement','{}'::jsonb,'semantic_complete',false),repeat('a',64)),'Edited source excerpts are rejected');
select ok(not private.knowledge_report_valid(jsonb_build_object('action','needs_review','matches',jsonb_build_array(jsonb_build_object('id','document:a','hash',repeat('d',64),'text','index lesson')),'relationships','[]'::jsonb,'warnings','[]'::jsonb,'placement','{}'::jsonb,'semantic_complete',false),repeat('a',64)),'An excerpt with the wrong source hash is rejected');
select ok(not private.knowledge_report_valid(jsonb_build_object('action','needs_review','matches',jsonb_build_array(jsonb_build_object('id','document:a','hash',repeat('c',64),'text','')),'relationships','[]'::jsonb,'warnings','[]'::jsonb,'placement','{}'::jsonb,'semantic_complete',false),repeat('a',64)),'An empty excerpt cannot support a nonempty source');
select ok(not private.knowledge_report_valid(jsonb_build_object('action','needs_review','matches',jsonb_build_array(jsonb_build_object('id','document:a','hash',repeat('c',64),'text',123)),'relationships','[]'::jsonb,'warnings','[]'::jsonb,'placement','{}'::jsonb,'semantic_complete',false),repeat('a',64)),'Evidence text must be a string');
select throws_ok($$select public.knowledge_publish('{"id":"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd","source_catalog_id":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","counts":{},"resources":[],"relationships":[{"id":"bad","source":"missing","target":"document:a","type":"related","provenance":"explicit"}]}'::jsonb)$$,'23514','Invalid graph references','Broken graph cannot activate');
select is((select snapshot_id from public.knowledge_state where id),repeat('a',64),'Failed upload preserves active graph');
select is((select count(*)::integer from public.knowledge_resources),1,'Failed upload leaves no partial rows');
select throws_ok($$select public.knowledge_publish('{"id":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","source_catalog_id":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","resources":[{"id":"document:a","kind":"document","title":"Changed","hash":"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","text":"Changed","visibility":"curriculum"}],"relationships":[]}'::jsonb)$$,'P0001','Immutable snapshot differs','Snapshot identity is immutable');
select throws_ok($$select public.knowledge_publish('{"id":"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd","source_catalog_id":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","resources":[{"id":"x","text":"No hash","visibility":"private"}],"relationships":[]}'::jsonb)$$,'23514','Invalid graph references','Missing hashes are rejected');
insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) values
('11111111-1111-4111-8111-111111111111','knowledge-admin@example.test',now(),now(),now()),
('22222222-2222-4222-8222-222222222222','knowledge-reader@example.test',now(),now(),now());
select public.linkedin_bootstrap_admin('11111111-1111-4111-8111-111111111111');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"22222222-2222-4222-8222-222222222222","role":"authenticated"}',true);
select is((select count(*)::integer from public.knowledge_resources),0,'Ordinary users cannot see curriculum projections or private data');
select throws_ok($$select public.knowledge_jobs_recent()$$,'42501','Admin access required','Ordinary users cannot list candidate jobs');
select throws_ok($$select public.knowledge_submit('{"title":"A","body":"Valid candidate","kind":"document"}','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')$$,'42501','Admin access required','Ordinary users cannot submit');
select set_config('request.jwt.claims','{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}',true);
select is(jsonb_array_length(public.knowledge_browse()->'resources'),1,'Admin can browse saved catalog offline');
select throws_ok($$select * from public.knowledge_jobs$$,'42501',null,'Even admin clients cannot read lease tokens');
select lives_ok($$select public.knowledge_submit('{"title":"A","body":"Valid candidate","kind":"document"}','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')$$,'Admin queues work');
select lives_ok($$select public.knowledge_submit('{"title":"A","body":"Valid candidate","kind":"document"}','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')$$,'Repeat submit is idempotent');
select throws_ok($$select public.knowledge_submit('{"title":"B","body":"Other candidate","kind":"document"}','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')$$,'P0001','Idempotency key belongs to another candidate','Key cannot be reused for changed content');
select throws_ok($$select public.knowledge_submit('{"title":"B","body":"Other candidate","kind":"hosted"}','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb')$$,'P0001','Invalid candidate','Invalid types rejected');
select is(public.knowledge_job('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')->>'status','pending','Offline submission remains queued');
reset role;
create temp table kg_claim as select public.knowledge_claim() data;
select is((select data->>'status' from kg_claim),'running','Worker acquires lease');
select is(public.knowledge_claim(),null::jsonb,'Concurrent claim cannot steal lease');
select throws_ok($$select public.knowledge_complete((data->>'id')::uuid,gen_random_uuid(),jsonb_build_object('snapshot_id',repeat('b',64),'candidate_hash',data->>'candidate_hash')) from kg_claim$$,'P0001','Expired knowledge lease','Wrong token rejected');
select throws_ok($$select public.knowledge_complete((data->>'id')::uuid,(data->>'lease_token')::uuid,jsonb_build_object('snapshot_id',repeat('b',64),'candidate_hash','changed')) from kg_claim$$,'P0001','Stale knowledge result','Changed candidate rejected');
select lives_ok($$select public.knowledge_complete((data->>'id')::uuid,(data->>'lease_token')::uuid,jsonb_build_object('snapshot_id',repeat('b',64),'candidate_hash',data->>'candidate_hash','relationships','[]'::jsonb,'matches','[]'::jsonb,'warnings','[]'::jsonb,'placement','{}'::jsonb,'action','needs_review','semantic_complete',false)) from kg_claim$$,'Bound result saved');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}',true);
select ok(not (public.knowledge_job('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa') ? 'lease_token'),'Job RPC omits leases');
select is(jsonb_array_length(public.knowledge_jobs_recent()),1,'Reports persist across browser sessions');
select throws_ok($$select public.knowledge_review('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','changed',repeat('b',64),'accept')$$,'P0001','Stale knowledge review','Stale approval rejected');
select lives_ok($$select public.knowledge_review('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',public.knowledge_job('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')->>'candidate_hash',repeat('b',64),'accept')$$,'Exact report can be reviewed');
reset role;
select is((select count(*)::integer from public.knowledge_relationships),0,'Review never mutates authored relationships');
update public.knowledge_jobs set status='running',attempts=3,leased_until=now()-interval '1 minute';
select is(public.knowledge_claim(),null::jsonb,'Exhausted lease is not retried');
select is((select status from public.knowledge_jobs),'failed','Exhausted lease becomes terminal');
select public.knowledge_publish(jsonb_build_object('id',repeat('e',64),'source_catalog_id',repeat('f',64),'resources',jsonb_build_array(jsonb_build_object('id','post:private','text','Private quoted evidence','hash',repeat('c',64),'visibility','private')),'relationships','[]'::jsonb,'semantic_complete',false));
update public.knowledge_jobs set status='succeeded',snapshot_id=repeat('e',64),report=jsonb_build_object('relationships',jsonb_build_array(jsonb_build_object('id','private-edge','source','post:private','target','post:private','type','related','provenance','inferred','evidence',jsonb_build_array(jsonb_build_object('resourceId','post:private','hash',repeat('c',64),'quote','Private quoted evidence')))));
select is(public.knowledge_apply_private('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),1,'Private edge application records the approved evidence');
select is((select applied_at from public.knowledge_jobs),null::timestamptz,'Private application cannot finish a mixed sidecar job prematurely');
select is(public.knowledge_apply_private('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),1,'Interrupted sidecar application can replay private edges idempotently');
select is((select count(*)::integer from public.knowledge_private_relationships),1,'Private replay does not duplicate the ledger');
select * from finish();
rollback;
