begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) values('11111111-1111-4111-8111-111111111111','create@example.test',now(),now(),now());
select public.linkedin_bootstrap_admin('11111111-1111-4111-8111-111111111111');
set local role anon;
select throws_ok($$select public.linkedin_create('test','Title','Topic','Body')$$,'42501',null,'anonymous creation denied');
reset role;
set local role authenticated;
select throws_ok($$select public.linkedin_create('test','Title','Topic','Body')$$,'42501','Admin access required','non-admin creation denied');
select set_config('request.jwt.claims','{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}',true);
select lives_ok($$select public.linkedin_create('test',' Title ',' Topic ',' Body ')$$,'admin creates a manual draft');
select is((select count(*)::int from public.linkedin_posts),1,'one post');
select is((select origin from public.linkedin_posts),'manual','honest manual provenance');
select is((select sources from public.linkedin_revisions),'[]'::jsonb,'no invented source material');
select is((select status from public.linkedin_posts),'review','starts in review');
select is((select count(*)::int from public.linkedin_jobs where kind='refine' and status='pending'),1,'analysis automatically queued');
select lives_ok($$select public.linkedin_create('test','Title','Topic','Body')$$,'retry is idempotent');
select is((select count(*)::int from public.linkedin_jobs),1,'retry does not duplicate work');
select throws_ok($$select public.linkedin_create('test','Changed','Topic','Body')$$,'P0001','This request already created a different draft. Refresh the collection.','ambiguous retries cannot create a different post');
select throws_ok($$select public.linkedin_create('oversize','Title','Topic',repeat('𝗔',1501))$$,'22023',null,'UTF-16 limit enforced in RPC');
select throws_ok($$select public.linkedin_create('empty','Title','Topic',' ')$$,'22023',null,'empty post denied');
select throws_ok($$select public.linkedin_review(id,current_revision_id,'approve') from public.linkedin_posts$$,'P0001','Analyze this manual post and use the proposed revision before approval.','manual initial cannot be approved');
reset role;
create temp table claim as select public.linkedin_claim('refine') payload;
select public.linkedin_complete_refine((payload#>>'{job,id}')::uuid,(payload#>>'{job,lease_token}')::uuid,'{"rewrittenPost":"Analyzed body","postingPlan":{"firstComment":""},"diagnosis":{},"alternativeHooks":["a","b","c"],"keyChanges":["a","b","c"],"verificationNotes":["Verify the facts"]}', repeat('a',64)) from claim;
set local role authenticated;
select throws_ok($$select public.linkedin_review(id,current_revision_id,'approve') from public.linkedin_posts$$,'P0001','Analyze this manual post and use the proposed revision before approval.','analysis never auto-adopts');
select public.linkedin_review(p.id,p.current_revision_id,'use',p_proposal_id=>r.id) from public.linkedin_posts p join public.linkedin_revisions r on r.post_id=p.id and r.kind='refine';
select throws_ok($$select public.linkedin_review(id,current_revision_id,'approve') from public.linkedin_posts$$,'P0001','Resolve placeholders and verify flagged facts before approval.','flagged facts still require review');
select public.linkedin_review(id,current_revision_id,'save',p_body=>'Analyzed body',p_first_comment=>'',p_facts_confirmed=>true) from public.linkedin_posts;
select is((select prompt_hash from public.linkedin_revisions where id=(select current_revision_id from public.linkedin_posts)),repeat('a',64),'facts-only confirmation retains analyzed identity');
select lives_ok($$select public.linkedin_review(id,current_revision_id,'approve') from public.linkedin_posts$$,'reviewed manual post can be approved');
reset role;
select public.linkedin_configure('fixture-channel','fixture-org',true);
create temp table schedule_claim as select public.linkedin_claim('schedule') payload;
select public.linkedin_begin_publish((payload#>>'{job,id}')::uuid,(payload#>>'{job,lease_token}')::uuid) from schedule_claim;
select public.linkedin_reconcile(id,current_revision_id,'{"status":"scheduled","buffer_id":"manual-fixture"}') from public.linkedin_posts;
set local role authenticated;
select public.linkedin_review(id,current_revision_id,'withdraw') from public.linkedin_posts;
reset role;
select public.linkedin_claim('cancel');
select public.linkedin_reconcile(id,current_revision_id,'{"status":"cancelled","buffer_id":"manual-fixture"}') from public.linkedin_posts;
set local role authenticated;
select lives_ok($$select public.linkedin_review(id,current_revision_id,'approve') from public.linkedin_posts$$,'cancelled analyzed manual revision can be reapproved');
select is((select prompt_hash from public.linkedin_revisions where id=(select current_revision_id from public.linkedin_posts)),repeat('a',64),'reapproval preserves analysis hash for the publishing gate');
select isnt((select current_revision_id from public.linkedin_posts),(select revision_id from public.linkedin_publications),'reapproval uses a fresh publication identity');
select public.linkedin_review(id,current_revision_id,'withdraw') from public.linkedin_posts;
select public.linkedin_review(id,current_revision_id,'save',p_body=>'Changed after analysis',p_first_comment=>'',p_facts_confirmed=>true) from public.linkedin_posts;
select throws_ok($$select public.linkedin_review(id,current_revision_id,'approve') from public.linkedin_posts$$,'P0001','Analyze this manual post and use the proposed revision before approval.','edited text must be analyzed again');
select is((select analysis from public.linkedin_revisions where id=(select current_revision_id from public.linkedin_posts)),null::jsonb,'old analysis is not presented as analysis of edited text');
select lives_ok($$select public.linkedin_create('test','Title','Topic','Body')$$,'retry finds initial content even after revisions');
select is((select count(*)::int from public.linkedin_posts),1,'no duplicate after revisions');
reset role;
select throws_ok($$insert into public.linkedin_revisions(post_id,kind,body,sources) select id,'edit',repeat('𝗔',1501),'[]'::jsonb from public.linkedin_posts$$,'23514',null,'table also enforces styled character limit');
select * from finish();
rollback;
