begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
select has_table('public', 'linkedin_posts', 'editorial posts exist');
select has_table('public', 'linkedin_revisions', 'revisions exist');
select has_function('public', 'linkedin_is_admin', array[]::text[], 'admin predicate exists');

insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) values
('11111111-1111-4111-8111-111111111111','editor@example.test',now(),now(),now()),
('22222222-2222-4222-8222-222222222222','reader@example.test',now(),now(),now()),
('33333333-3333-4333-8333-333333333333','unverified@example.test',null,now(),now());
select throws_ok($$select public.linkedin_bootstrap_admin('33333333-3333-4333-8333-333333333333')$$, 'P0001', 'A verified personal account is required','cannot bootstrap an unverified identity');
select public.linkedin_bootstrap_admin('11111111-1111-4111-8111-111111111111');
select is(public.linkedin_import('[{"seed_key":"one","title":"Retries","topic":"Reliability","body":"Retries consume capacity.","sources":[{"path":"test","hash":"abc","title":"Test","excerpt":"Retry limits","urls":[]}]}]'),1,'imports one review draft');
select is(public.linkedin_import('[{"seed_key":"one","title":"Overwrite","topic":"Wrong","body":"Changed","sources":[{}]}]'),0,'repeated seed never replaces reviewed material');
set constraints all immediate;
set constraints all deferred;
create temp table editorial_ids as select id post_id,current_revision_id revision_id from public.linkedin_posts where seed_key='one';
grant select,update on editorial_ids to authenticated,service_role;

set local role anon;
select is(public.linkedin_is_admin(),false,'anon is not an admin');
select throws_ok($$select * from public.linkedin_posts$$,'42501',null,'anon cannot read drafts');
select throws_ok($$select public.linkedin_snapshot()$$,'42501',null,'anon cannot call snapshot');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"22222222-2222-4222-8222-222222222222","role":"authenticated"}',true);
select is((select count(*)::integer from public.linkedin_posts),0,'ordinary users see no editorial rows');
select throws_ok($$select public.linkedin_snapshot()$$,'42501','Admin access required','snapshot refuses ordinary users');
select throws_ok($$insert into private.app_admins(user_id) values('22222222-2222-4222-8222-222222222222')$$,'42501',null,'no self elevation');
select throws_ok($$select public.linkedin_bootstrap_admin('22222222-2222-4222-8222-222222222222')$$,'42501',null,'bootstrap is privileged');
select throws_ok($$select public.linkedin_claim('refine')$$,'42501',null,'clients cannot claim worker jobs');
select throws_ok($$select public.linkedin_review(post_id,revision_id,'approve') from editorial_ids$$,'42501','Admin access required','ordinary users cannot approve');
select set_config('request.jwt.claims','{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}',true);
select is(public.linkedin_is_admin(),true,'allowlisted user is admin');
select is((select count(*)::integer from public.linkedin_posts),1,'admin can read drafts');
select throws_ok($$update public.linkedin_posts set status='approved'$$,'42501',null,'admins cannot bypass approval RPC');
select lives_ok($$select public.linkedin_snapshot()$$,'admin snapshot succeeds');
select public.linkedin_review(post_id,revision_id,'refine') from editorial_ids;
select public.linkedin_review(post_id,revision_id,'refine') from editorial_ids;
select is((select count(*)::integer from public.linkedin_jobs),1,'double clicks enqueue one active job');
reset role;
create temp table claimed as select public.linkedin_claim('refine') payload;
select is((select payload#>>'{job,status}' from claimed),'running','job is claimed');
select is(public.linkedin_claim('refine'),null::jsonb,'second worker cannot claim the same job');
select throws_ok($$select public.linkedin_renew((payload#>>'{job,id}')::uuid,gen_random_uuid()) from claimed$$,'40001','Job lease is no longer valid','wrong lease token rejected');
select lives_ok($$select public.linkedin_renew((payload#>>'{job,id}')::uuid,(payload#>>'{job,lease_token}')::uuid) from claimed$$,'valid lease can renew');
set local role authenticated;
select public.linkedin_review(post_id,revision_id,'save','New draft text.','') from editorial_ids;
select throws_ok($$select public.linkedin_review(post_id,revision_id,'approve') from editorial_ids$$,'40001','The draft changed. Refresh before continuing.','stale approval rejected');
reset role;
select public.linkedin_complete_refine((payload#>>'{job,id}')::uuid,(payload#>>'{job,lease_token}')::uuid,
'{"rewrittenPost":"Better retry explanation.","diagnosis":{},"alternativeHooks":["a","b","c"],"postingPlan":{"firstComment":"Sources"},"verificationNotes":[]}',repeat('a',64)) from claimed;
select is((select status from public.linkedin_posts where seed_key='one'),'review','worker does not approve');
select is((select r.body from public.linkedin_revisions r join public.linkedin_posts p on p.current_revision_id=r.id where p.seed_key='one'),'New draft text.','stale refinement does not replace edited content');
select throws_ok($$update public.linkedin_revisions set body='rewritten in place'$$,'55000','Editorial revisions are immutable','service cannot overwrite history');
update editorial_ids set revision_id=(select current_revision_id from public.linkedin_posts where seed_key='one');
set local role authenticated;
select throws_ok($$select public.linkedin_review(post_id,revision_id,'use',p_proposal_id=>(select id from public.linkedin_revisions where kind='refine')) from editorial_ids$$,'40001','This proposal is based on an older draft. Refine the current revision.','stale proposal cannot be adopted');
select public.linkedin_review(post_id,revision_id,'save','We saved [ADD: metric]','') from editorial_ids;
update editorial_ids set revision_id=(select current_revision_id from public.linkedin_posts where seed_key='one');
select throws_ok($$select public.linkedin_review(post_id,revision_id,'approve') from editorial_ids$$,'P0001','Resolve placeholders and verify flagged facts before approval.','placeholders block publication');
select public.linkedin_review(post_id,revision_id,'save','A bounded retry policy reduces amplification.','') from editorial_ids;
update editorial_ids set revision_id=(select current_revision_id from public.linkedin_posts where seed_key='one');
select public.linkedin_review(post_id,revision_id,'approve') from editorial_ids;
select is((select approved_revision_id from public.linkedin_posts),(select revision_id from editorial_ids),'approval binds exact revision');
select throws_ok($$select public.linkedin_review(post_id,revision_id,'save','Silent replacement','') from editorial_ids$$,'P0001','Return this post to review before editing or refining.','approved text is locked');
reset role;
select is(public.linkedin_claim('schedule'),null::jsonb,'disabled publisher does not claim approvals');
select public.linkedin_configure('channel','org',true);
truncate claimed;
insert into claimed select public.linkedin_claim('schedule');
select public.linkedin_begin_publish((payload#>>'{job,id}')::uuid,(payload#>>'{job,lease_token}')::uuid) from claimed;
select throws_ok($$select public.linkedin_begin_publish((payload#>>'{job,id}')::uuid,(payload#>>'{job,lease_token}')::uuid) from claimed$$,'P0001','A publication already exists. Reconcile instead of sending again.','cannot issue a duplicate publish');
select public.linkedin_fail((payload#>>'{job,id}')::uuid,(payload#>>'{job,lease_token}')::uuid,'network timeout',true) from claimed;
select is(public.linkedin_claim('schedule'),null::jsonb,'ambiguous publish is not retried');
select is((select status from public.linkedin_publications),'unknown','ambiguous publication remains unknown');
select public.linkedin_reconcile(post_id,revision_id,'{"status":"scheduled","buffer_id":"external1","scheduled_at":"2026-10-01T10:00:00Z"}') from editorial_ids;
select is((select status from public.linkedin_publications),'scheduled','reconciliation confirms external schedule');
set local role authenticated;
select public.linkedin_review(post_id,revision_id,'withdraw') from editorial_ids;
select is((select status from public.linkedin_posts),'withdrawing','withdraw waits for Buffer cancellation');
reset role;
select public.linkedin_claim('cancel');
select public.linkedin_reconcile(post_id,revision_id,'{"status":"cancelled","buffer_id":"external1"}') from editorial_ids;
select is((select status from public.linkedin_posts),'review','confirmed cancellation returns draft to review');
select is((select approved_revision_id from public.linkedin_posts),null::uuid,'withdraw removes approval');


select throws_ok($$select public.linkedin_restore('{"version":1}')$$,'P0001','Restore requires an empty editorial collection; export existing data first.','restore never replaces live editorial data');
set local role authenticated;
select public.linkedin_review(post_id,revision_id,'approve') from editorial_ids;
select isnt((select approved_revision_id from public.linkedin_posts),(select revision_id from editorial_ids),'reapproval after cancellation gets a new publication identity');
select public.linkedin_review(id,current_revision_id,'withdraw') from public.linkedin_posts;
select public.linkedin_review(id,current_revision_id,'refine') from public.linkedin_posts;
reset role;
truncate claimed;
insert into claimed select public.linkedin_claim('refine');
update public.linkedin_jobs set lease_until=now()-interval '1 minute' where status='running';
select throws_ok($$select public.linkedin_renew((payload#>>'{job,id}')::uuid,(payload#>>'{job,lease_token}')::uuid) from claimed$$,'40001','Job lease is no longer valid','expired lease cannot write');
select is((public.linkedin_claim('refine')#>>'{job,attempts}')::integer,2,'expired refinement can be reclaimed');
update public.linkedin_jobs set lease_until=now()-interval '1 minute' where status='running';
select is((public.linkedin_claim('refine')#>>'{job,attempts}')::integer,3,'third attempt is allowed');
update public.linkedin_jobs set lease_until=now()-interval '1 minute' where status='running';
select is(public.linkedin_claim('refine'),null::jsonb,'retry count is bounded');
select is((select count(*)::integer from public.linkedin_jobs where kind='refine' and status='failed'),1,'exhausted refinement remains visible');
select * from finish();
rollback;
