begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
select public.linkedin_restore('{"version":1,"posts":[],"revisions":[],"jobs":[],"publications":[],"settings":[{"author_context":"Restored author","buffer_channel_id":"restored-channel","buffer_organization_id":"restored-org","timezone":"Europe/London","publishing_enabled":true}]}');
select is((select author_context from public.linkedin_settings),'Restored author','restore preserves author context');
select is((select buffer_channel_id from public.linkedin_settings),'restored-channel','restore preserves destination');
select is((select timezone from public.linkedin_settings),'Europe/London','restore preserves timezone');
select is((select publishing_enabled from public.linkedin_settings),false,'restore always pauses publishing');
insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) values('11111111-1111-4111-8111-111111111111','editor@example.test',now(),now(),now());
select public.linkedin_bootstrap_admin('11111111-1111-4111-8111-111111111111');
select public.linkedin_import('[{"seed_key":"race","title":"Race","topic":"Reliability","body":"Cancellation can race publication.","sources":[{}]}]');
select set_config('request.jwt.claims','{"sub":"11111111-1111-4111-8111-111111111111","role":"authenticated"}',true);
select public.linkedin_review(id,current_revision_id,'approve') from public.linkedin_posts;
select public.linkedin_configure('channel','org',true);
create temp table claimed as select public.linkedin_claim('schedule') payload;
select public.linkedin_begin_publish((payload#>>'{job,id}')::uuid,(payload#>>'{job,lease_token}')::uuid) from claimed;
select public.linkedin_reconcile(id,current_revision_id,'{"status":"scheduled","buffer_id":"race-id"}') from public.linkedin_posts;
select public.linkedin_review(id,current_revision_id,'withdraw') from public.linkedin_posts;
select public.linkedin_claim('cancel');
select public.linkedin_reconcile(id,current_revision_id,'{"status":"sent","buffer_id":"race-id","sent_at":"2026-09-29T00:00:00Z"}') from public.linkedin_posts;
select is((select status from public.linkedin_posts),'approved','already sent publication exits withdrawing state');
select is((select status from public.linkedin_jobs where kind='cancel'),'failed','cancellation cannot remain running after publication');
select is((select lease_token from public.linkedin_jobs where kind='cancel'),null::uuid,'terminal cancellation releases lease');
select throws_ok($$select public.linkedin_review(id,current_revision_id,'withdraw') from public.linkedin_posts$$,'P0001','This post has already been published.','sent publication cannot be withdrawn');
select * from finish();
rollback;
