import { build } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const wasm = await readFile(require.resolve("sql.js/dist/sql-wasm.wasm"));
const result = await build({
  entryPoints: ["scripts/game/sql-worker.ts"],
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  minify: true,
  define: { GAME_SQL_WASM: JSON.stringify(wasm.toString("base64")) },
});
const notices = await Promise.all(
  ["sql.js", "sqlite-parser", "css-tree"].map(
    async (name) =>
      `${name}\n${await readFile(join(dirname(dirname(require.resolve(name))), "LICENSE"), "utf8")}`,
  ),
);
const worker =
  `/*! Bundled dependencies\n${notices.join("\n\n").replaceAll("*/", "* /")}\n*/\n` +
  result.outputFiles[0].text;
await mkdir("apps/web/public/game", { recursive: true });
await mkdir("apps/mobile/src/generated", { recursive: true });
await writeFile("apps/web/public/game/sql-worker.js", worker);
await writeFile(
  "apps/mobile/src/generated/game-worker.ts",
  `// Generated by npm run game:runtime. Do not edit.\nexport const gameWorkerSource=${JSON.stringify(worker)};\n`,
);
console.log(
  `Bundled local SQLite worker (${worker.length} bytes) for web and native.`,
);
