import { readFile, writeFile } from "node:fs/promises";
import { gameCampaignSchema } from "../../packages/core/src/game/schema";
const campaign = gameCampaignSchema.parse(
  JSON.parse(await readFile("content/game/restore-the-signal.json", "utf8")),
);
const steps: (object | string)[] = [
  { launchApp: { clearState: true } },
  { setAirplaneMode: "enabled" },
];
let rank = 0;
function find(selector: object, next: number) {
  steps.push({
    scrollUntilVisible: {
      element: selector,
      direction: next < rank ? "UP" : "DOWN",
      centerElement: true,
      timeout: 20000,
    },
  });
  rank = next;
}
function tap(id: string, next: number) {
  find({ id }, next);
  steps.push({ tapOn: { id } });
}
for (const level of campaign.levels) {
  steps.push({ openLink: `codematica://play/${campaign.id}/${level.id}` });
  rank = 0;
  steps.push({
    runFlow: {
      when: { visible: "Open in.*Codematica.*" },
      commands: [{ tapOn: "Open" }],
    },
  });
  for (const scenario of level.scenarios) {
    tap(`game-scenario-${scenario.id}`, 10);
    if (scenario.kind === "grid" || scenario.kind === "sql") {
      tap("game-code", 50);
      steps.push(
        { eraseText: scenario.starter.length },
        { inputText: scenario.solution },
        "hideKeyboard",
      );
    } else if (scenario.kind === "pipes") {
      const ports = scenario.pieces.flatMap((p) => p.ports);
      for (const e of scenario.solution) {
        tap(
          `game-port-${e.from}`,
          100 + ports.findIndex((p) => p.id === e.from),
        );
        tap(`game-port-${e.to}`, 100 + ports.findIndex((p) => p.id === e.to));
      }
    } else {
      if (level.mode === "defense" && scenario.id !== "main")
        tap("game-assist", 700);
      for (const id of scenario.solution.nodes)
        tap(
          `game-piece-${id}`,
          100 + scenario.components.findIndex((c) => c.id === id),
        );
      for (const e of scenario.solution.edges) {
        tap(`game-connect-${e.from}`, 200);
        tap(`game-connect-${e.to}`, 200);
      }
      if (scenario.solution.routing === "capacity-weighted")
        tap("game-routing", 250);
      if (scenario.solution.invalidate) tap("game-invalidate", 270);
    }
    tap("game-run", 600);
    if (level.mode === "defense" && scenario.id === "main") {
      steps.push(
        { pressKey: "Home" },
        { launchApp: { stopApp: false } },
        { assertVisible: { id: "game-resume" } },
        { tapOn: { id: "game-resume" } },
      );
      steps.push({
        extendedWaitUntil: {
          visible: "Integrity.*24/24s.*won",
          timeout: 40000,
        },
      });
    }
    find({ text: "Signal restored!" }, 1000);
    steps.push({ assertVisible: "Signal restored!" });
  }
  // A full restart must keep all earned objectives while discarding the attempt.
  steps.push("launchApp");
  rank = 0;
}
steps.push(
  { setAirplaneMode: "disabled" },
  { openLink: "codematica://" },
  {
    scrollUntilVisible: {
      element: { text: ".*36/36.*1800 XP.*" },
      direction: "UP",
    },
  },
  { assertVisible: ".*36/36.*1800 XP.*" },
);
await writeFile(
  "apps/mobile/.maestro/game-chapter.regression.yaml",
  `# Generated by npm run game:flows; solutions come from validated campaign content.\nappId: com.codematica.app\ntags:\n  - regression\nonFlowComplete:\n  - setAirplaneMode: disabled\n---\n${JSON.stringify(steps, null, 2)}\n`,
);
console.log(
  `Exported the 36-scenario native chapter journey (${steps.length} actions).`,
);
