"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState, useSyncExternalStore } from "react";
import { BriefcaseBusiness, Download, Plus, RefreshCw, Save, UserRound, X, Pencil } from "lucide-react";
import { briefSchema, createInterviewClient, exportBrief, opportunityInputSchema, opportunityStatuses, preparationState, roundSchema, sectionLabels, type InterviewClient, type InterviewSnapshot, type Opportunity, type OpportunityInput } from "@codematica/core/interview-preparation";
import { createInterviewStore, type InterviewStore } from "@codematica/core/interview-preparation-store";
import { createBrowserSupabaseClient } from "@/lib/supabase/client";
import { AppHeader } from "./AppHeader";
import { Button } from "./Button";
import { Dropdown } from "./Dropdown";
import { MarkdownRenderer } from "./MarkdownRenderer";

export function InterviewPreparationAdmin({ client }: { client?: InterviewClient | null }) {
 const api=useMemo(()=>{const db=client===undefined?createBrowserSupabaseClient():null;return client===undefined?db&&createInterviewClient(db):client;},[client]);
 const store=useMemo(()=>createInterviewStore(api),[api]); const state=useSyncExternalStore(store.subscribe,store.getSnapshot,store.getSnapshot);
 const [selected,setSelected]=useState<string|null>(null),[mode,setMode]=useState<"read"|"edit"|"create"|"profile"|"import">("read"),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[prep,setPrep]=useState("all");
 const search=useRef<HTMLInputElement>(null); const opener=useRef<HTMLButtonElement|null>(null);
 useEffect(()=>{void store.refresh();return api?.onAccessChange(()=>{store.resetAccess();setMode("read");setSelected(null);void store.refresh();});},[store,api]);
 useEffect(()=>{if(!state.editing)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard);},[state.editing]);
 const data=state.data; const current=data?.opportunities.find(o=>o.id===selected);
 function close(){store.discard();setMode("read");requestAnimationFrame(()=>{if(opener.current?.isConnected)opener.current.focus();else search.current?.focus();});}
 function open(next:typeof mode){store.startEditing();setMode(next);}
 const filtered=data?.opportunities.filter(o=>{const revision=data.revisions.find(r=>r.brief.opportunityId===o.id);const ps=preparationState(revision?.brief??null,o.version,data.profile.version,data.graphSnapshot);return `${o.company} ${o.position}`.toLowerCase().includes(query.toLowerCase())&&(status==="all"||o.status===status)&&(prep==="all"||(prep==="stale"?ps.stale:ps.status===prep));})??[];
 const groups=new Map<string,Opportunity[]>(); for(const opportunity of filtered) groups.set(opportunity.companyId,[...(groups.get(opportunity.companyId)??[]),opportunity]);
 return <><main className="interview-admin" data-testid="interview-admin"><AppHeader subtitle="Admin"/>
  <header className="interview-heading"><div><BriefcaseBusiness aria-hidden="true"/><h1>Interview preparation</h1><p>Private opportunities, research and practice.</p></div><div className="ui-actions"><Button label="Your experience" icon={UserRound} disabled={state.editing||state.phase!=="ready"} onClick={()=>open("profile")}/><Button label="New opportunity" icon={Plus} tone="info" disabled={state.editing||state.phase!=="ready"} onClick={()=>open("create")}/><Button label="Refresh" icon={RefreshCw} disabled={state.editing||state.busy||state.phase!=="ready"} onClick={()=>void store.refresh()}/></div></header>
  {state.error?<p role="alert">{state.error}</p>:null}
  {state.phase==="unavailable"?<p>Configure Supabase to use the private interview tracker.</p>:state.phase==="denied"?<p>Admin access required. <Link href="/login">Sign in</Link> with your admin account.</p>:state.phase==="loading"?<p role="status">Loading interviews…</p>:data?<>
   {mode==="profile"?<ProfileForm data={data} store={store} onClose={close}/>:mode==="create"||mode==="edit"?<OpportunityForm key={current?.id??"new"} opportunity={mode==="edit"?current:undefined} store={store} onClose={(id)=>{if(id)setSelected(id);close();}}/>:mode==="import"&&current?<ImportForm opportunity={current} store={store} onClose={close}/>:<>
    <div className="interview-filters"><label>Search companies<input ref={search} className="ui-input" value={query} onChange={e=>setQuery(e.target.value)} /></label><Dropdown label="Opportunity status" value={status} options={[{value:"all",label:"All statuses"},...opportunityStatuses.map(value=>({value,label:value}))]} onValueChange={setStatus}/><Dropdown label="Preparation" value={prep} options={["all","missing","draft","prepared","stale"].map(value=>({value,label:value==="all"?"All preparation":value==="stale"?"Needs refresh":value}))} onValueChange={setPrep}/></div>
    <div className="interview-workspace" data-selected={!!current}><section className="interview-collection" aria-label="Companies">
     {!filtered.length?<p>{data.opportunities.length?"No matching opportunities.":"No interview opportunities yet."}</p>:null}
     {[...groups.entries()].map(([id,opportunities])=><div key={id} className="interview-company"><h2>{opportunities[0].company}</h2>{opportunities.map(o=>{const revision=data.revisions.find(r=>r.brief.opportunityId===o.id);const ps=preparationState(revision?.brief??null,o.version,data.profile.version,data.graphSnapshot);const next=o.rounds.filter(r=>r.scheduledAt&&Date.parse(r.scheduledAt)>Date.now()).sort((a,b)=>Date.parse(a.scheduledAt)-Date.parse(b.scheduledAt))[0];return <button key={o.id} className="interview-opportunity" aria-pressed={selected===o.id} data-testid={`interview-opportunity-${o.id}`} onClick={e=>{opener.current=e.currentTarget;setSelected(o.id);}}><strong>{o.position}</strong><span>{o.status} · {ps.status}{ps.stale?" · Needs refresh":""}</span>{next?<span>Next: {new Date(next.scheduledAt).toLocaleString(undefined,{timeZone:next.timezone})} ({next.timezone})</span>:null}</button>;})}</div>)}
    </section>{current?<section className="interview-detail"><Button label="Back to companies" variant="quiet" onClick={()=>{setSelected(null);close();}}/><OpportunityDetail key={current.id} opportunity={current} data={data} store={store} onEdit={()=>open("edit")} onImport={()=>open("import")}/></section>:<p className="interview-empty">Select an opportunity to prepare.</p>}</div>
   </>}
  </>:null}
 </main></>;
}
function Field({label,value,onChange,multiline=false,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;multiline?:boolean;disabled?:boolean}){return <label className="interview-field">{label}{multiline?<textarea className="ui-input" value={value} onChange={e=>onChange(e.target.value)} disabled={disabled} rows={5}/>:<input className="ui-input" value={value} onChange={e=>onChange(e.target.value)} disabled={disabled}/>}</label>;}
function ProfileForm({data,store,onClose}:{data:InterviewSnapshot;store:InterviewStore;onClose:()=>void}){
 const [resume,setResume]=useState(data.profile.resume),[experience,setExperience]=useState(data.profile.experience);const busy=store.getSnapshot().busy;
 return <section className="interview-form"><h2>Your experience</h2><p>Paste your resume and project stories. Include source links, your responsibilities and verified outcomes. Missing details remain explicit in preparation.</p><Field label="Resume" value={resume} onChange={setResume} multiline disabled={busy}/><Field label="Project stories and evidence" value={experience} onChange={setExperience} multiline disabled={busy}/><div className="ui-actions"><Button label="Save profile" icon={Save} tone="info" disabled={busy} onClick={()=>void store.saveProfile({resume,experience},data.profile.version).then(ok=>{if(ok)onClose();})}/><Button label="Discard changes" icon={X} disabled={busy} onClick={onClose}/></div></section>;
}
function OpportunityForm({opportunity,store,onClose}:{opportunity?:Opportunity;store:InterviewStore;onClose:(id?:string)=>void}){
 const [input,setInput]=useState<OpportunityInput>(()=>opportunity??opportunityInputSchema.parse({company:"New company",position:"New position"}));
 const [error,setError]=useState("");const busy=store.getSnapshot().busy; const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus();},[]);
 function change(key:keyof OpportunityInput,value:string){setInput(v=>({...v,[key]:value}));}
 async function save(){const parsed=opportunityInputSchema.safeParse(input);if(!parsed.success){setError(parsed.error.issues[0].message);return;}const id=await store.save(parsed.data,opportunity?.id??null,opportunity?.version??0);if(id)onClose(id);}
 return <section className="interview-form"><h2 tabIndex={-1} ref={heading}>{opportunity?"Edit opportunity":"New opportunity"}</h2>{error?<p role="alert">{error}</p>:null}
  {([['company','Company'],['website','Company website'],['position','Position'],['jobUrl','Job posting URL'],['jobDescription','Job description'],['notes','Notes'],['outcome','Outcome']] as const).map(([key,label])=><Field key={key} label={label} value={input[key]} onChange={value=>change(key,value)} multiline={["jobDescription","notes","outcome"].includes(key)} disabled={busy}/>)}
  <Dropdown label="Status" value={input.status} options={opportunityStatuses.map(value=>({value,label:value}))} onValueChange={value=>change("status",value)} disabled={busy}/>
  <h3>Interview rounds</h3>{input.rounds.map((round,i)=><fieldset key={i}><legend>Round {i+1}</legend>{([['label','Round name'],['scheduledAt','Date/time with UTC offset'],['timezone','Timezone'],['format','Format'],['interviewer','Interviewer'],['interviewerTitle','Interviewer title'],['profileUrl','Interviewer profile URL'],['notes','Round notes']] as const).map(([key,label])=><Field key={key} label={label} value={round[key]} onChange={value=>setInput(v=>({...v,rounds:v.rounds.map((r,j)=>j===i?{...r,[key]:value}:r)}))} disabled={busy}/>)}<p>For example: 2026-10-05T10:00:00-07:00, timezone America/Los_Angeles. Leave the date blank if unknown.</p><Button label="Remove round" tone="danger" disabled={busy} onClick={()=>setInput(v=>({...v,rounds:v.rounds.filter((_,j)=>j!==i)}))}/></fieldset>)}
  <div className="ui-actions"><Button label="Add round" icon={Plus} disabled={busy||input.rounds.length>=50} onClick={()=>setInput(v=>({...v,rounds:[...v.rounds,roundSchema.parse({label:"New round"})]}))}/><Button label="Save opportunity" icon={Save} tone="info" variant="primary" disabled={busy} onClick={()=>void save()}/><Button label="Discard changes" icon={X} disabled={busy} onClick={()=>onClose()}/></div>
 </section>;
}
function ImportForm({opportunity,store,onClose}:{opportunity:Opportunity;store:InterviewStore;onClose:()=>void}){
 const [value,setValue]=useState(""),[error,setError]=useState("");const busy=store.getSnapshot().busy;
 async function save(){try{const brief=briefSchema.parse(JSON.parse(value));if(brief.opportunityId!==opportunity.id)throw new Error("This brief belongs to another opportunity.");const id=await store.importBrief(brief);if(id)onClose();}catch(e){setError(e instanceof Error?e.message:"Invalid brief");}}
 return <section className="interview-form"><h2>Import preparation</h2><p>Paste the preparation package produced by the prepare-interview skill. It must include a technical-edit comparison receipt.</p><Field label="Preparation package" value={value} onChange={setValue} multiline disabled={busy}/>{error?<p role="alert">{error}</p>:null}<div className="ui-actions"><Button label="Import brief" icon={Save} tone="info" disabled={busy} onClick={()=>void save()}/><Button label="Discard changes" disabled={busy} onClick={onClose}/></div></section>;
}
function OpportunityDetail({opportunity:o,data,store,onEdit,onImport}:{opportunity:Opportunity;data:InterviewSnapshot;store:InterviewStore;onEdit:()=>void;onImport:()=>void}){
 const [revisionId,setRevisionId]=useState<string|null>(null),[exported,setExported]=useState(false);const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus();},[]);
 const history=data.revisions.filter(r=>r.brief.opportunityId===o.id);const selected=history.find(r=>r.id===revisionId)??history[0];const brief=selected?.brief;const ps=preparationState(brief??null,o.version,data.profile.version,data.graphSnapshot);
 function download(){if(!brief)return;const blob=new Blob([exportBrief(`${selected?.context?.company??o.company} — ${selected?.context?.position??o.position}`,brief)],{type:"text/markdown;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`interview-${o.id}.md`;a.click();URL.revokeObjectURL(url);setExported(true);}
 return <><h2 ref={heading} tabIndex={-1}>{o.company} — {o.position}</h2><p>{o.status} · {ps.status}{ps.stale?" · Needs refresh: preparation inputs changed.":""}</p><div className="ui-actions"><Button label="Edit opportunity" icon={Pencil} onClick={onEdit}/><Button label="Import preparation" icon={Plus} tone="assist" onClick={onImport}/><Button label="Export Markdown" icon={Download} disabled={!brief} onClick={download}/><Button label="Archive opportunity" disabled={store.getSnapshot().busy||o.status==="archived"} onClick={()=>void store.save({...o,status:"archived"},o.id,o.version)}/></div>{exported?<p role="status">Exported the selected saved revision.</p>:null}
 <details><summary>Generate or refresh preparation</summary><p>In Codex, invoke <code>$prepare-interview</code> for this opportunity: <code>{o.id}</code>. The skill researches, personalizes, applies technical-edit, and saves a new brief.</p>{!data.profile.resume?<p>Add your resume in Your experience for stronger personalization.</p>:null}</details>
 {brief?<>{brief.knowledge.warnings.map((w,i)=><p key={i} role="status">{w}</p>)}{Object.entries(sectionLabels).map(([key,label])=><section key={key}><h3>{label}</h3><MarkdownRenderer markdown={brief.sections[key as keyof typeof sectionLabels]}/></section>)}<section><h3>Study resources</h3>{brief.resources.map(r=><p key={r.resourceId}>{r.route?<Link href={r.route}>{r.title}</Link>:r.title}<br/>{r.quote}</p>)}</section><details><summary>Sources and provenance</summary>{brief.sources.map((s,i)=><p key={i}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a> · {s.kind} · verified {s.verifiedAt}</p>)}<p>Edited with technical-edit. Input versions: {brief.opportunityVersion}/{brief.profileVersion}.</p></details></>:<p>No preparation yet. Add your experience, then invoke the preparation skill.</p>}
 <details><summary>Opportunity and rounds</summary>{o.website?<a href={o.website} target="_blank" rel="noreferrer">Company website</a>:null}{o.jobUrl?<p><a href={o.jobUrl} target="_blank" rel="noreferrer">Job posting</a></p>:null}<p className="interview-preserve">{o.jobDescription}</p><p className="interview-preserve">{o.notes}</p><p className="interview-preserve">{o.outcome}</p>{o.rounds.map((r,i)=><div key={i}><h3>{r.label}</h3><p>{r.interviewer} · {r.interviewerTitle} · {r.format}</p><p>{r.scheduledAt?new Date(r.scheduledAt).toLocaleString(undefined,{timeZone:r.timezone}):"Date unknown"} · {r.timezone}</p>{r.profileUrl?<a href={r.profileUrl} target="_blank" rel="noreferrer">Interviewer profile</a>:null}<p>{r.notes}</p></div>)}</details>
 <details><summary>Revision history ({history.length})</summary>{history.map(r=><Button key={r.id} label={`Read revision ${new Date(r.createdAt).toLocaleString()}`} onClick={()=>{setRevisionId(r.id);setExported(false);}}/>)}</details>
 </>;
}
