import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe,expect,it,vi } from 'vitest';
import { InterviewPreparationAdmin } from './InterviewPreparationAdmin';
const snapshot={profile:{version:0,resume:'',experience:''},opportunities:[],revisions:[]};
function api(){return {isAdmin:vi.fn().mockResolvedValue(true),snapshot:vi.fn().mockResolvedValue(snapshot),save:vi.fn().mockResolvedValue('11111111-1111-4111-8111-111111111111'),saveProfile:vi.fn().mockResolvedValue(undefined),importBrief:vi.fn(),onAccessChange:vi.fn(()=>()=>{})};}
vi.mock('./AppHeader',()=>({AppHeader:()=>null}));
describe('interview admin',()=>{
 it('shows missing configuration and refuses non-admin access',async()=>{const {unmount}=render(<InterviewPreparationAdmin client={null}/>);expect(screen.getByText(/Configure Supabase/)).toBeVisible();unmount();const client=api();client.isAdmin.mockResolvedValue(false);render(<InterviewPreparationAdmin client={client}/>);expect(await screen.findByText(/Admin access required/)).toBeVisible();expect(client.snapshot).not.toHaveBeenCalled();});
 it('creates an opportunity, preserves failed input and exposes round fields',async()=>{const client=api();client.save.mockRejectedValueOnce(new Error('Offline'));render(<InterviewPreparationAdmin client={client}/>);await screen.findByText('No interview opportunities yet.');fireEvent.click(screen.getByRole('button',{name:'New opportunity'}));fireEvent.change(screen.getByLabelText('Company'),{target:{value:'Example'}});fireEvent.change(screen.getByLabelText('Position'),{target:{value:'Engineer'}});fireEvent.click(screen.getByRole('button',{name:'Add round'}));expect(screen.getByLabelText('Interviewer')).toBeVisible();fireEvent.change(screen.getByLabelText('Round name'),{target:{value:'Technical'}});fireEvent.click(screen.getByRole('button',{name:'Save opportunity'}));expect(await screen.findByText('Offline')).toBeVisible();expect(screen.getByLabelText('Company')).toHaveValue('Example');fireEvent.click(screen.getByRole('button',{name:'Save opportunity'}));await waitFor(()=>expect(client.save).toHaveBeenCalledTimes(2));});
 it('edits a private profile without discarding failed input',async()=>{const client=api();render(<InterviewPreparationAdmin client={client}/>);await screen.findByText('No interview opportunities yet.');fireEvent.click(screen.getByRole('button',{name:'Your experience'}));fireEvent.change(screen.getByLabelText('Resume'),{target:{value:'Actual experience'}});fireEvent.click(screen.getByRole('button',{name:'Save profile'}));await waitFor(()=>expect(client.saveProfile).toHaveBeenCalledWith({resume:'Actual experience',experience:''},0));});
});

import {sampleBrief} from '../../../../packages/core/src/test/interview-preparation-fixture';
import {opportunityInputSchema} from '@codematica/core/interview-preparation';
const opportunity={...opportunityInputSchema.parse({company:'Example',position:'Engineer',jobDescription:'Role description',notes:'Private note',outcome:'Outcome',rounds:[{label:'Architecture',scheduledAt:'2099-10-05T10:00:00-07:00',interviewer:'Person',interviewerTitle:'CTO',format:'Discussion',profileUrl:'https://example.com/person',notes:'Round note'}]}),id:sampleBrief.opportunityId,companyId:sampleBrief.opportunityId,version:2,updatedAt:'2026-10-04'};
function populated(){const client=api();client.snapshot.mockResolvedValue({profile:{version:1,resume:'Resume',experience:'Evidence'},opportunities:[opportunity],revisions:[{id:sampleBrief.opportunityId,createdAt:'2026-10-04',brief:{...sampleBrief,resources:[{resourceId:'path:example',title:'Study example',hash:'a'.repeat(64),quote:'Literal',route:'/paths/example',paths:[],skills:[]}]}},{id:'22222222-2222-4222-8222-222222222222',createdAt:'2026-10-03',brief:sampleBrief}]} as never);return client;}
describe('interview reading and import',()=>{
 it('reads history and exports saved prose without regeneration',async()=>{
  const client=populated();const revoke=vi.fn();Object.defineProperty(URL,'createObjectURL',{configurable:true,value:vi.fn(()=> 'blob:example')});Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:revoke});vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});
  render(<InterviewPreparationAdmin client={client}/>);fireEvent.click(await screen.findByRole('button',{name:/Engineer/}));expect(screen.getByText(/Needs refresh: preparation inputs changed/)).toBeVisible();expect(screen.getByRole('link',{name:'Study example'})).toHaveAttribute('href','/paths/example');
  fireEvent.click(screen.getByText('Sources and provenance'));expect(screen.getByRole('link',{name:'Company'})).toHaveAttribute('href','https://example.com');fireEvent.click(screen.getByRole('button',{name:'Export Markdown'}));expect(revoke).toHaveBeenCalled();expect(screen.getByText('Exported the selected saved revision.')).toBeVisible();
  fireEvent.click(screen.getByText(/Revision history/));fireEvent.click(screen.getAllByRole('button',{name:/Read revision/})[1]);expect(screen.queryByRole('link',{name:'Study example'})).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole('button',{name:'Archive opportunity'}));await waitFor(()=>expect(client.save).toHaveBeenCalledWith(expect.objectContaining({status:'archived'}),opportunity.id,2,expect.any(String)));
 });
 it('keeps invalid imports and failed submissions recoverable',async()=>{
  const client=populated();client.importBrief.mockResolvedValue(sampleBrief.opportunityId);render(<InterviewPreparationAdmin client={client}/>);fireEvent.click(await screen.findByRole('button',{name:/Engineer/}));fireEvent.click(screen.getByRole('button',{name:'Import preparation'}));fireEvent.change(screen.getByLabelText('Preparation package'),{target:{value:'invalid'}});fireEvent.click(screen.getByRole('button',{name:'Import brief'}));expect(await screen.findByRole('alert')).toBeVisible();
  fireEvent.change(screen.getByLabelText('Preparation package'),{target:{value:JSON.stringify({...sampleBrief,opportunityId:'22222222-2222-4222-8222-222222222222'})}});fireEvent.click(screen.getByRole('button',{name:'Import brief'}));expect(await screen.findByText('This brief belongs to another opportunity.')).toBeVisible();
  fireEvent.change(screen.getByLabelText('Preparation package'),{target:{value:JSON.stringify(sampleBrief)}});fireEvent.click(screen.getByRole('button',{name:'Import brief'}));await waitFor(()=>expect(client.importBrief).toHaveBeenCalled());
 });
 it('edits round details and preserves fields until explicit discard',async()=>{
  const client=populated();render(<InterviewPreparationAdmin client={client}/>);fireEvent.click(await screen.findByRole('button',{name:/Engineer/}));fireEvent.click(screen.getByRole('button',{name:'Edit opportunity'}));fireEvent.change(screen.getByLabelText('Interviewer'),{target:{value:'Updated'}});fireEvent.change(screen.getByLabelText('Company website'),{target:{value:'file:///bad'}});fireEvent.click(screen.getByRole('button',{name:'Save opportunity'}));expect(await screen.findByRole('alert')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Remove round'}));expect(screen.queryByLabelText('Interviewer')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Discard changes'}));expect(screen.getByRole('heading',{name:'Example — Engineer'})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Back to companies'}));
  fireEvent.change(screen.getByLabelText('Search companies'),{target:{value:'no match'}});expect(screen.getByText('No matching opportunities.')).toBeVisible();
 });
});
