// Independently reviewed answers to the declared original paper cases.
export const evidenceAnswers: Record<string, readonly string[]> = {
  "ai-engineering/local-decision-contracts": [
    "The expected index is 1.3; it is not a correctness percentage.",
    "Keep the alternative and missing evidence visible; hold application for review.",
    "Bind the readout and cache to the new ordered option identities.",
    "Judge purpose and added value; lesson-to-post reuse can be useful.",
    "Measure inference, latency and memory separately; output count proves no cost or licensing claim.",
  ],
  "software-engineering/credential-containment": [
    "Contain active harm promptly and record the continuity tradeoff.",
    "The acting principal; identifying the human or workload requires more evidence.",
    "That key route changed; the issued token needs a separate validity and access check.",
    "Build A is verified; Release B remains unverified.",
    "No use was found within the searched scope; external consumers remain unknown.",
  ],
  "programming/java-state-and-proxy-contracts": [
    "Require stable key equality and review the record’s nested ownership separately.",
    "Both write 5; volatile does not make the increment atomic.",
    "Remove request context on the owning thread, including exceptional exits.",
    "Self-invocation bypasses that proxy advice; inspect the actual intercepted entry.",
    "Checked exceptions do not trigger rollback by default; explicit or global rules can change this.",
  ],
  "software-engineering/domain-and-deployment-boundaries": [
    "Record each context’s meaning and translate explicitly across the boundary.",
    "The booking’s identity; value equality is a separate policy.",
    "One protected capacity-and-allocation transition for the stated invariant.",
    "Modules describe ownership and dependencies; processes add separate runtime and failure scope.",
    "Booking acceptance is evidenced; billing completion still needs its own receipt.",
  ],
  "system-design/cloud-responsibility-and-runtime": [
    "The application’s data and access policy need their own owner and verification.",
    "Inspect shared-kernel, mount, capability and daemon authority; packaging alone proves no isolation.",
    "Bob may inherit stale request state; separate reusable clients from user context.",
    "Asynchronous acceptance; function completion needs a separate outcome record.",
    "The alert reports delayed usage; it did not act as a universal spending cap.",
  ],
  "system-design/federation-and-delegation": [
    "B’s local session remains separate and needs its own configured login flow.",
    "Reject it for this client despite the valid signature.",
    "Reject the mismatch before using the returned tokens.",
    "Reject the exchange; a verifier cannot retroactively establish the missing challenge.",
    "Only if the resource’s current refund authorization check permits that action.",
  ],
  "system-design/card-payment-state-evidence": [
    "Request acceptance; issuer authorization and settlement need separate receipts.",
    "Authorization is evidenced; capture remains a separate pending operation.",
    "Inspect C7 and preserve its idempotent operation identity before deciding on a retry.",
    "20 units; settlement still needs its own receipt.",
    "Retain capture and record the refund as a separate operation with its own outcome.",
  ],
  "creative-computing/authoritative-motion-and-prediction": [
    "10.4 metres.",
    "10.8 metres, while the true current position remains unverified.",
    "Keep 12 as authoritative; reject the older update.",
    "Presentation smoothing must not replace authoritative gameplay checks.",
    "A defined time mapping before subtracting timestamps for prediction age.",
  ],
  "creative-computing/sampled-surfaces-and-time": [
    "0.5 metres.",
    "0.25 seconds under this declared mapping.",
    "0 metres because the two phase terms cancel.",
    "An appearance effect; geometric displacement needs a separate operation.",
    "Intervals per cycle fall from four to two; inspect the sampled shape separately.",
  ],
  "creative-computing/blockout-and-trigger-state": [
    "Appearance does not establish a traversable collision route.",
    "Check overlap-event configuration on both participating collision components.",
    "The exit remains closed; filter the actor before activation.",
    "The exit is open with one activation.",
    "Reject the old-session event; the reset state belongs to the new session.",
  ],
  "business/ownership-and-funding-models": [
    "60% and 40% of the 1,000 issued shares.",
    "20% of 1,250 shares; existing holders’ fractions change.",
    "The selling holder; the company’s issued-share total need not increase.",
    "Keep that denominator and contract scope explicit; later dilution and rights require separate terms.",
    "One sixth of 1,500 issued shares.",
  ],
};

export const evidenceSources: Record<string, string> = {
  "evidence-openjev-readout": "https://github.com/abhishekgahlot2/openjev-server/blob/032a2c5791f3d8856cc26fdb6876c106fac8dbf8/openjev_server/readout.py",
  "evidence-openjev-license": "https://github.com/abhishekgahlot2/openjev-server/blob/032a2c5791f3d8856cc26fdb6876c106fac8dbf8/README.md",
  "evidence-google-containment": "https://docs.cloud.google.com/docs/security/compromised-credentials",
  "evidence-google-service-accounts": "https://docs.cloud.google.com/iam/docs/best-practices-service-accounts",
  "evidence-java23-map": "https://docs.oracle.com/en/java/javase/23/docs/api/java.base/java/util/Map.html",
  "evidence-jls23-memory": "https://docs.oracle.com/javase/specs/jls/se23/html/jls-17.html",
  "evidence-jls23-records": "https://docs.oracle.com/javase/specs/jls/se23/html/jls-8.html",
  "evidence-java23-threadlocal": "https://docs.oracle.com/en/java/javase/23/docs/api/java.base/java/lang/ThreadLocal.html",
  "evidence-spring-transactions": "https://docs.spring.io/spring-framework/reference/data-access/transaction/declarative/annotations.html",
  "evidence-ddd-reference": "https://www.domainlanguage.com/wp-content/uploads/2016/05/DDD_Reference_2015-03.pdf",
  "evidence-cloud-responsibility": "https://cloud.google.com/learn/paas-vs-iaas-vs-saas",
  "evidence-container-security": "https://docs.docker.com/engine/security/",
  "evidence-lambda-reuse": "https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html",
  "evidence-lambda-acceptance": "https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html",
  "evidence-lambda-uniqueness": "https://docs.aws.amazon.com/lambda/latest/dg/snapstart-uniqueness.html",
  "evidence-aws-budget": "https://docs.aws.amazon.com/cost-management/latest/userguide/budgets-managing-costs.html",
  "evidence-oidc-core": "https://openid.net/specs/openid-connect-core-1_0.html",
  "evidence-pkce": "https://www.rfc-editor.org/rfc/rfc7636.html",
  "evidence-oauth-security": "https://www.rfc-editor.org/rfc/rfc9700.html",
  "evidence-stripe-hold": "https://docs.stripe.com/payments/place-a-hold-on-a-payment-method",
  "evidence-visa-flow": "https://developer.visa.com/capabilities/visanet-connect-acceptance/docs-getting-started",
  "evidence-unity-anticipation": "https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/c25748c7e67375d3bd4657f389ec5b3bf6aff382/docs/advanced-topics/client-anticipation.md",
  "evidence-blender-scene-time": "https://docs.blender.org/manual/en/5.2/modeling/geometry_nodes/input/scene/scene_time.html",
  "evidence-blender-position": "https://docs.blender.org/manual/en/5.2/modeling/geometry_nodes/geometry/read/position.html",
  "evidence-unreal-triggers": "https://dev.epicgames.com/documentation/en-us/unreal-engine/trigger-volume-actors-in-unreal-engine",
  "evidence-unreal-overlap": "https://dev.epicgames.com/documentation/en-us/unreal-engine/BlueprintAPI/Collision/OnActorBeginOverlap",
  "evidence-yc-safe": "https://www.ycombinator.com/safe"
};
