import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { languageAudioCatalogFileSchema } from "../../packages/core/src/content/schema";

export type JapaneseAudioBuildOptions = {
  rootDir?: string;
};

export async function buildJapaneseAudio({
  rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../.."),
}: JapaneseAudioBuildOptions = {}) {
  const contentDir = path.join(rootDir, "content/languages/japanese");
  const manifestPath = path.join(contentDir, "audio-manifest.json");
  const webAudioDir = path.join(rootDir, "apps/web/public/japanese-audio");
  const webRegistryPath = path.join(rootDir, "apps/web/src/generated/japanese-audio.ts");
  const mobileRegistryPath = path.join(rootDir, "apps/mobile/src/generated/japanese-audio.ts");
  const manifest = languageAudioCatalogFileSchema.parse(
    JSON.parse(await fs.readFile(manifestPath, "utf8")),
  );

  await fs.mkdir(webAudioDir, { recursive: true });
  await fs.mkdir(path.dirname(webRegistryPath), { recursive: true });
  await fs.mkdir(path.dirname(mobileRegistryPath), { recursive: true });

  const webEntries: string[] = [];
  const mobileEntries: string[] = [];
  const approved = manifest.items.filter((asset) => asset.qaStatus === "approved");

  for (const asset of approved) {
    const source = path.resolve(contentDir, asset.assetPath);
    if (!source.startsWith(`${contentDir}${path.sep}`)) {
      throw new Error(`Audio asset ${asset.id} escapes Japanese content.`);
    }
    await fs.access(source);
    const extension = path.extname(asset.assetPath);
    const webFileName = `${asset.id}${extension}`;
    await fs.copyFile(source, path.join(webAudioDir, webFileName));
    webEntries.push(`  ${JSON.stringify(asset.id)}: ${JSON.stringify(`/japanese-audio/${webFileName}`)},`);
    mobileEntries.push(`  ${JSON.stringify(asset.id)}: require(${JSON.stringify(`../../../../content/languages/japanese/${asset.assetPath}`)}),`);
  }

  const header = "// Generated by npm run content:audio. Do not edit by hand.\n";
  await fs.writeFile(webRegistryPath, `${header}export const japaneseAudioUrls = {\n${webEntries.join("\n")}\n} as const;\n`, "utf8");
  await fs.writeFile(mobileRegistryPath, `${header}export const japaneseAudioAssets = {\n${mobileEntries.join("\n")}\n} as const;\n`, "utf8");

  return { assets: approved.length, drafts: manifest.items.filter((asset) => asset.qaStatus === "draft").length, webRegistryPath, mobileRegistryPath };
}

/* v8 ignore start -- the CLI entry point delegates to the tested build helper. */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const result = await buildJapaneseAudio();
  console.log(`Prepared ${result.assets} Japanese audio assets.`);
}
/* v8 ignore stop */
