import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { buildJapaneseAudio } from "./build-japanese-audio";

const roots: string[] = [];

async function makeRoot(items: unknown[]) {
  const rootDir = await mkdtemp(path.join(os.tmpdir(), "codematica-audio-"));
  roots.push(rootDir);
  const contentDir = path.join(rootDir, "content/languages/japanese");
  await mkdir(contentDir, { recursive: true });
  await writeFile(
    path.join(contentDir, "audio-manifest.json"),
    JSON.stringify({ kind: "audio", language: "ja", items }),
  );
  return { rootDir, contentDir };
}

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe("Japanese audio registry generation", () => {
  it("writes deterministic empty registries", async () => {
    const { rootDir } = await makeRoot([]);
    await expect(buildJapaneseAudio({ rootDir })).resolves.toMatchObject({ assets: 0 });
    await expect(readFile(path.join(rootDir, "apps/web/src/generated/japanese-audio.ts"), "utf8")).resolves.toBe(
      "// Generated by npm run content:audio. Do not edit by hand.\nexport const japaneseAudioUrls = {\n\n} as const;\n",
    );
  });

  it("copies released audio and writes stable web and native entries", async () => {
    const item = {
      id: "kana-a",
      transcript: "あ",
      reading: "a",
      speaker: "Test Speaker",
      license: "Original",
      attribution: "Codematica test fixture",
      assetPath: "audio/kana-a.mp3",
      qaStatus: "approved",
      disclosure: "Human-recorded voice",
    };
    const { rootDir, contentDir } = await makeRoot([item]);
    await mkdir(path.join(contentDir, "audio"));
    await writeFile(path.join(contentDir, item.assetPath), "fixture-audio");

    const result = await buildJapaneseAudio({ rootDir });
    expect(result.assets).toBe(1);
    await expect(readFile(path.join(rootDir, "apps/web/public/japanese-audio/kana-a.mp3"), "utf8")).resolves.toBe("fixture-audio");
    await expect(readFile(result.webRegistryPath, "utf8")).resolves.toContain('"kana-a": "/japanese-audio/kana-a.mp3"');
    await expect(readFile(result.mobileRegistryPath, "utf8")).resolves.toContain('require("../../../../content/languages/japanese/audio/kana-a.mp3")');
  });

  it("excludes draft generated audio from runtime registries", async () => {
    const item = {
      id: "draft-audio",
      transcript: "学生です。",
      reading: "がくせいです。",
      speaker: "OpenAI marin",
      license: "OpenAI generated output",
      attribution: "Generated for Codematica",
      assetPath: "audio/draft-audio.mp3",
      qaStatus: "draft",
      disclosure: "AI-generated voice",
      provenance: { kind: "openai-tts", model: "gpt-4o-mini-tts", voice: "marin", instructions: "Speak clear Japanese.", generatedAt: "2026-08-09T00:00:00.000Z", checksum: "b".repeat(64) },
    };
    const { rootDir, contentDir } = await makeRoot([item]);
    await mkdir(path.join(contentDir, "audio"));
    await writeFile(path.join(contentDir, item.assetPath), "fixture-audio");

    await expect(buildJapaneseAudio({ rootDir })).resolves.toMatchObject({ assets: 0, drafts: 1 });
    await expect(readFile(path.join(rootDir, "apps/web/src/generated/japanese-audio.ts"), "utf8")).resolves.not.toContain("draft-audio");
  });

  it("rejects missing files and paths outside the audio contract", async () => {
    const validMissing = {
      id: "missing-audio",
      transcript: "あ",
      reading: "a",
      speaker: "Test Speaker",
      license: "Original",
      attribution: "Codematica test fixture",
      assetPath: "audio/missing.mp3",
      qaStatus: "approved",
      disclosure: "Human-recorded voice",
    };
    const missing = await makeRoot([validMissing]);
    await expect(buildJapaneseAudio({ rootDir: missing.rootDir })).rejects.toThrow();

    const traversal = await makeRoot([{ ...validMissing, assetPath: "../secret.mp3" }]);
    await expect(buildJapaneseAudio({ rootDir: traversal.rootDir })).rejects.toThrow();
  });
});
