import {act,fireEvent,render,waitFor} from '@testing-library/react-native';
import {InterviewPreparationScreen} from '../../../../packages/ui/src/InterviewPreparationScreen';
const snapshot={profile:{version:0,resume:'',experience:''},opportunities:[],revisions:[]};
function api(){return {isAdmin:jest.fn().mockResolvedValue(true),snapshot:jest.fn().mockResolvedValue(snapshot),save:jest.fn().mockResolvedValue('11111111-1111-4111-8111-111111111111'),saveProfile:jest.fn(),importBrief:jest.fn(),onAccessChange:jest.fn((listener:()=>void)=>{void listener;return()=>{};})};}
describe('native interview preparation',()=>{
 it('requires configuration',async()=>{const view=await render(<InterviewPreparationScreen client={null} onNavigate={jest.fn()}/>);expect(view.getByText(/Configure Supabase/)).toBeOnTheScreen();});
 it('creates a private opportunity with labeled touch controls',async()=>{const client=api();const view=await render(<InterviewPreparationScreen client={client} onNavigate={jest.fn()}/>);await waitFor(()=>expect(view.getByText('No interview opportunities yet.')).toBeOnTheScreen());await fireEvent.press(view.getByText('New opportunity'));await fireEvent.changeText(view.getByLabelText('Company'),'Example');await fireEvent.changeText(view.getByLabelText('Position'),'Engineer');await fireEvent.press(view.getByText('Save opportunity'));await waitFor(()=>expect(client.save).toHaveBeenCalled());});
});

import {Share} from 'react-native';
import {sampleBrief} from '../../../../packages/core/src/test/interview-preparation-fixture';
import {opportunityInputSchema} from '../../../../packages/core/src/interview-preparation';
const opportunity={...opportunityInputSchema.parse({company:'Example',position:'Engineer',rounds:[{label:'Technical',interviewer:'Person'}]}),id:sampleBrief.opportunityId,companyId:sampleBrief.opportunityId,version:1,updatedAt:'2026-10-04'};
function populated(){const client=api();client.snapshot.mockResolvedValue({profile:{version:1,resume:'Resume',experience:'Story'},opportunities:[opportunity],revisions:[{id:sampleBrief.opportunityId,createdAt:'2026-10-04',brief:{...sampleBrief,resources:[{resourceId:'path:example',hash:'a'.repeat(64),title:'Study example',quote:'Literal',route:'/paths/example',paths:[],skills:[]}]}}]});return client;}
describe('native reading, editing and exports',()=>{
 it('reads saved preparation, follows study links and shares exact Markdown',async()=>{
  const client=populated();const navigate=jest.fn();const share=jest.spyOn(Share,'share').mockResolvedValue({action:Share.sharedAction});const view=await render(<InterviewPreparationScreen client={client} onNavigate={navigate}/>);await waitFor(()=>expect(view.getByText('Engineer')).toBeOnTheScreen());await fireEvent.press(view.getByText('Engineer'));expect(view.getByText(sampleBrief.sections.questionsToAsk)).toBeOnTheScreen();await fireEvent.press(view.getByText('Study example'));expect(navigate).toHaveBeenCalledWith('/paths/example');await fireEvent.press(view.getByText('Export Markdown'));expect(share).toHaveBeenCalledWith(expect.objectContaining({message:expect.stringContaining(sampleBrief.sections.questionsToAsk)}));await fireEvent.press(view.getByText('Read revision 2026-10-04'));await fireEvent.press(view.getByText('Archive opportunity'));await waitFor(()=>expect(client.save).toHaveBeenCalledWith(expect.objectContaining({status:'archived'}),opportunity.id,1,expect.any(String)));await fireEvent.press(view.getByText('Back to companies'));
 });
 it('edits rounds and profile, validates imports and preserves save failures',async()=>{
  const client=populated();client.saveProfile.mockResolvedValue(undefined);client.importBrief.mockResolvedValue(sampleBrief.opportunityId);const view=await render(<InterviewPreparationScreen client={client} onNavigate={jest.fn()}/>);await waitFor(()=>expect(view.getByText('Engineer')).toBeOnTheScreen());await fireEvent.press(view.getByText('Your experience'));await fireEvent.changeText(view.getByLabelText('Resume'),'Updated resume');await fireEvent.changeText(view.getByLabelText('Project stories and evidence'),'Updated story');await fireEvent.press(view.getByText('Save profile'));await waitFor(()=>expect(client.saveProfile).toHaveBeenCalledWith({resume:'Updated resume',experience:'Updated story'},1));
  await fireEvent.press(view.getByText('Engineer'));await fireEvent.press(view.getByText('Edit opportunity'));await fireEvent.changeText(view.getByLabelText('Interviewer'),'Changed');await fireEvent.press(view.getByText('Remove round'));await fireEvent.press(view.getByText('Add round'));await fireEvent.changeText(view.getByLabelText('Round name'),'New technical round');await fireEvent.press(view.getByText('interviewing'));await fireEvent.press(view.getByText('Discard changes'));
  await fireEvent.press(view.getByText('Import preparation'));await fireEvent.changeText(view.getByLabelText('Preparation package'),'invalid');await fireEvent.press(view.getByText('Import brief'));expect(client.importBrief).not.toHaveBeenCalled();await fireEvent.changeText(view.getByLabelText('Preparation package'),JSON.stringify(sampleBrief));await fireEvent.press(view.getByText('Import brief'));await waitFor(()=>expect(client.importBrief).toHaveBeenCalled());
 });
 it('clears private records on account change and denies ordinary users',async()=>{
  const client=populated();let callback!:()=>void;client.onAccessChange.mockImplementation(fn=>{callback=fn;return()=>{};});const view=await render(<InterviewPreparationScreen client={client} onNavigate={jest.fn()}/>);await waitFor(()=>expect(view.getByText('Engineer')).toBeOnTheScreen());client.isAdmin.mockResolvedValue(false);await act(async()=>callback());await waitFor(()=>expect(view.getByText('Admin access required.')).toBeOnTheScreen());expect(view.queryByText('Engineer')).toBeNull();
 });
});
